firecow/gitlab-ci-local

src/job.ts, src/parser.ts
This PR will add support for anonymous and predefined stages as documented here https://docs.gitlab.com/ee/ci/yaml/.
=> Mimic gitlab-org runner stages

src/job.ts, tests/cases.test.ts, tests/test-cases/image/.gitlab-ci.yml, tests/test-cases/image/test-file.txt
=> Fixed entrypoint pwd, and made sure entrypoint output actually gets caught

package-lock.json, package.json, src/asserts.ts, src/default-cmd.ts, src/job-expanders.ts, src/job.ts, src/parser.ts, src/types/job-options.ts
- Made predefined values extrapolate values from git remote.
- Added JobOptions interface instead of passing 1million params to Job class.
- Introduced assert function. Made throw new logic cleaner
=> Extrapolate predefines from git remote

src/job-expanders.ts, tests/cases.test.ts, tests/test-cases/extends/.gitlab-ci.yml
…merge, not deep-extends like the rest of the YAML
=> Fix bug with extends in multi levels. extends tag is deep-merge, not deep-extend

src/job.ts
=> Do not fail if no artifact

src/parser.ts, tests/test-cases/custom-home/.gitlab-ci.yml, tests/test-cases/custom-home/.home-normalize-key/.gitlab-ci-local/variables.yml, tests/test-cases/custom-home/integration.custom-home.test.ts
Normalize project url in `$HOME/.gitlab-ci-local/variables.yaml` to allow git ssh remote urls
=> Normalize project url

src/parser.ts
change regex to accept not secure remotes
=> accept not secure remote

.github/workflows/build.yml, package.json, src/job-expanders.ts, src/job.ts, src/parser.ts, src/types/job-options.ts, tests/test-cases/artifacts-shell/.gitlab-ci-when-never.yml, tests/test-cases/artifacts-shell/integration.artifacts-shell.test.ts, tests/test-cases/cache/.gitlab-ci.yml
- Implement cache being a list.
- when:never jobs shouldn't be considered producers
- Use nodejs 16
- actions/cache@v2 node_modules
=> Various improvements

src/parser.ts
https://github.com/firecow/gitlab-ci-local/issues/244#issuecomment-931595348
=> fix(include project file): define file input parameter for better-compatibility on tar command

src/job.ts
This PR is an amateur attempt at adding a generic service healthCheck function. It works by:
1. Using `docker inspect <service_name>` to identify a list of ports exposed by the image.
2. Runs an instance of [willwill/wait-for-it](https://hub.docker.com/r/willwill/wait-for-it) in docker, that wait for up to 30 seconds for the service to become available.
This logic was based on a small blurb on the [GitLab Services Page](https://docs.gitlab.com/ee/ci/services/#how-the-health-check-of-services-works)
> To make sure this works, the runner:
>
>    1. Checks which ports are exposed from the container by default.
>    2. Starts a special container that waits for these ports to be accessible. 
I'm not a JS developer, and this is literally the first time I've used TS. If I've done anything …
=> Add serviceHealthCheck

src/commander.ts, src/handler.ts, tests/test-cases/script-failures/.gitlab-ci.yml, tests/test-cases/script-failures/integration.script-failures.test.ts
=> Print last three lines on script failure or warning

README.md, src/argv.ts, src/index.ts, src/job.ts, src/variables-from-files.ts, tests/test-cases/remote-variables-file/.gitlab-ci.yml, tests/test-cases/remote-variables-file/integration.project-variables-file.test.ts
- Add --remote-variables option
- Expand environment.name and environment.url before envspecific expansions
- Reformat README.md and add section about --remote-variables
- Add autoCompleting to argv object, so we can "stall" certain tasks based
=> Remote variables

src/parser-includes.ts, tests/test-cases/include-project-file-ref-with-inner-local/mock-gitlab-module-with-local.yml
=> Fixed a bug with include expansion inside project file ref include

src/job.ts, src/validator.ts, tests/test-cases/cache-paths-not-array/.gitlab-ci.yml, tests/test-cases/cache-paths-not-array/integration.cache-paths-not-array.test.ts, tests/test-cases/script-blank/.gitlab-ci.yml, tests/test-cases/script-blank/integration.script-blank.test.ts
=> Validate blank script, and cache.paths must be array

src/argv.ts, src/commander.ts, src/handler.ts, src/index.ts
=> Implement only-needs option

src/argv.ts, src/commander.ts, src/handler.ts, src/index.ts
=> Add --list-json option

src/utils.ts, tests/test-cases/image/.gitignore, tests/test-cases/image/integration.image.test.ts
=> fix #452: rsync exludes files that it should not

src/job.ts
=> env expand cache.key

src/job-expanders.ts
=> Fix bug in job-expanders jobExtends function

src/utils.ts, tests/rules.test.ts
=> Fix issue with rules env expand and overzealous matching pattern

src/job.ts
=> Service healthchecking was broken, apparently!!

src/job.ts, src/utils.ts, tests/test-cases/project-variables-file/.gitlab-ci-local-variables.yml, tests/test-cases/project-variables-file/.gitlab-ci.yml, tests/test-cases/project-variables-file/integration.project-variables-file.test.ts
=> Expand variables recursively two times

src/job-expanders.ts, src/job.ts, src/parser.ts, tests/test-cases/cache-directives/.gitlab-ci.yml, tests/test-cases/cache-directives/integration.cache-directives.test.ts
=> Bug fix cache directives

src/job.ts
=> pages is not a reserverd word, apparently

src/cache-entry.ts, src/job-expanders.ts, src/job.ts, src/utils.ts, tests/test-cases/cache-docker/.gitlab-ci.yml, tests/test-cases/cache-docker/integration.cache-docker.test.ts
=> Make sure cache.key is properly expanded

src/validator.ts, tests/test-cases/dependencies-not-found/.gitlab-ci.yml, tests/test-cases/dependencies-not-found/integration.dependencies-not-found.test.ts, tests/test-cases/needs-unspecified-job/integration.needs-unspecified-job.test.ts
=> Validate dependencies instructions in validator.ts

src/job.ts, src/utils.ts, tests/test-cases/manual/.gitlab-ci.yml, tests/test-cases/manual/integration.manual.test.ts
=> Add rules variables feature

README.md, src/argv.ts, tests/test-cases/custom-home/.gitlab-ci.yml, tests/test-cases/custom-home/.home/.gitlab-ci-local/.env, tests/test-cases/custom-home/integration.custom-home.test.ts
=> Add $HOME/.gitlab-ci-local/.env support

README.md, src/argv.ts, src/index.ts, src/job.ts, tests/test-cases/artifacts-to-source-no/.gitlab-ci.yml, tests/test-cases/artifacts-to-source-no/integration.artifacts-to-source-no.test.ts
=> feat(#552): Adding global config artifactsToSource

src/data-expander.ts, src/parser.ts, tests/test-cases/variable-order/.gitlab-ci.yml
=> Make it possible to have an object as global variable "value"

.gitignore, package-lock.json, package.json, src/parser-includes.ts, src/parser.ts, src/utils.ts, tests/test-cases/include-local-wildcard/.gitlab-ci.yml, tests/test-cases/include-local-wildcard/build-images.gitlab-ci.yml, tests/test-cases/include-local-wildcard/cache-repo.gitlab-ci.yml, tests/test-cases/include-local-wildcard/docs.gitlab-ci.yml, tests/test-cases/include-local-wildcard/integration.include-local.test.ts
=> feat(197): Adding tests for include wildcard

src/job.ts
- Make sure artifact.reports.dotenv is expanded with environment variables (remote works this way)
- Fix bug when loading dotenv file with predefined variable value in its name.
=> Fix various bugs with artifact.reports.dotenv

package.json, src/job.ts, tests/test-cases/after-script/.gitlab-ci.yml, tests/test-cases/after-script/integration.after-script.test.ts
- Implement CI_JOB_STATUS
- Add a few eslint rules, that makes sense
closes #581
=> Implement CI_JOB_STATUS variable

src/commander.ts, src/job.ts, src/utils.ts, tests/test-cases/cache-docker-mount/.gitlab-ci.yml, tests/test-cases/cache-docker-mount/integration.cache-docker-mount.test.ts
=> Use safe docker string as docker volume, when mount-cache enabled

examples/docker-in-docker-build/.gitignore, examples/docker-in-docker-build/.gitlab-ci-local-env, examples/docker-in-docker-build/.gitlab-ci.yml, examples/docker-in-docker-build/Dockerfile, src/job.ts, tsconfig.json
- Fix bug in services healthcheck to pass on first available tcp port
closes #523
=> Add docker-in-docker example

src/job.ts, tests/test-cases/services/.gitlab-ci.yml
=> Don't start services and their networks in both pre_script and after_script exec's

src/job.ts
=> Only enter copyArtifacts routine if artifacts.paths present or artifacts.reports.dotenv is present

src/executor.ts, src/job.ts, src/validator.ts, tests/test-cases/needs-unspecified-job/integration.needs-unspecified-job.test.ts, tests/test-cases/never-needs/.gitlab-ci.yml, tests/test-cases/never-needs/integration.never-needs.test.ts
See: https://docs.gitlab.com/ee/ci/yaml/#needsoptional
=> Support optional needs

src/utils.ts, tests/rules.test.ts
=> trim double quotes from regexp string in rules

src/job.ts, tests/test-cases/services/integration.services.test.ts
=> Always put service container logs in .gitlab-ci-local/services-output

src/argv.ts, src/index.ts, src/job.ts
=> Add --clean/--no-cleanup cli option

src/job.ts
=> Use Config over ContainerConfig

src/job.ts
=> fix(596): Adding docker.io to gitlab-ci-local-util image references

src/job.ts, tests/test-cases/dind/.gitlab-ci-local-env, tests/test-cases/dind/.gitlab-ci.yml, tests/test-cases/dind/catme.txt, tests/test-cases/dind/integration.dind.test.ts
=> Copy source files into service containers like gitlab does

src/executor.ts, tests/test-cases/needs-optional-complex/.gitlab-ci.yml, tests/test-cases/needs-optional-complex/integration.needs-optional-complex.test.ts, tests/test-cases/needs-optional/.gitlab-ci.yml, tests/test-cases/needs-optional/integration.needs-optional.test.ts
=> fix(689): Adding case to execute pipelines with absent optional jobs

src/argv.ts, src/index.ts, src/job.ts, tests/test-cases/umask/.gitlab-ci.yml, tests/test-cases/umask/integration.umask-case.test.ts
=> feat: Adding --umask (default true) option

src/cache-entry.ts, src/data-expander.ts, src/job.ts, tests/test-cases/cache-when/.gitlab-ci.yml, tests/test-cases/cache-when/integration.cache-when.test.ts
Add support for cache:when (https://docs.gitlab.com/ee/ci/yaml/index.html#cachewhen)
closes #717
=> issue-717 (https://github.com/firecow/gitlab-ci-local/issues/717) 

package-lock.json, package.json, src/job.ts
=> Use split2 to properly handle output stream newline splitting

src/job.ts, tests/test-cases/needs-artifacts/.gitlab-ci.yml, tests/test-cases/needs-artifacts/integration.needs-artifacts.test.ts
=> Fix bug in needs: [{job: <name>}] systax handling

src/utils.ts, tests/test-cases/coverage/.gitlab-ci.yml, tests/test-cases/coverage/integration.coverage.test.ts
=> Fix coverage percent

src/job.ts
=> Make sure CI_REGISTRY and CI_REGISTRY_IMAGE are expanded recursively

src/validator.ts
=> Assert array of strings

src/data-expander.ts, src/parser.ts, tests/test-cases/reference/.gitlab-ci-complex.yml, tests/test-cases/reference/integration.reference.test.ts
=> extend before expanding !reference

src/utils.ts, tests/test-cases/project-variables-file/.gitlab-ci.yml
=> Cast vars to string, before string matching on them in expand recursive

src/argv.ts, src/index.ts, src/job.ts, src/parser.ts, src/predefined-variables.ts, tests/test-cases/plain/.gitlab-ci.yml, tests/test-cases/plain/integration.plain.test.ts
closes #729 
```
gitlab-ci-local --unset-variable CI_COMMIT_BRANCH
```
=> Add --unset-variable cli option

src/argv.ts, src/index.ts, src/job.ts
=> Add quiet option to suppress job's stdout and stderr output

src/parser-includes.ts, tests/test-cases/gitignore/.gitlab-ci-local/.gitignore, tests/test-cases/include-local/.gitlab-ci.yml
=> Remove leading slash in local includes

src/argv.ts
closes #779 
Make stuff like this possible
```
gitlab-ci-local --variable CI_COMMIT_REF='$CI_JOB_ID`
```
=> Allow all characters is value field 

src/commander.ts, src/job.ts, src/parser.ts, src/utils.ts
=> Refactored when variables gets expanded to avoid places where it could occur to early

src/index.ts
=> Set yargs configuration greed-arrays to false

src/utils.ts, tests/test-cases/coverage/.gitlab-ci.yml
=> Pick last match when doing coverage regexp'ing

src/parser-includes.ts, tests/test-cases/include-invalid-project-file-ref/integration.include-invalid-project-ref-file.test.ts, tests/test-cases/include-invalid-remote/integration.include-invalid-remote.test.ts
=> Print error, when project ref file include cannot be fetched, so devs can better debug

src/data-expander.ts, src/parser.ts, tests/test-cases/needs-parallel/.gitlab-ci.yml
Also add a little test to prevent this from happening again
https://github.com/firecow/gitlab-ci-local/pull/837
=> Fix a bug found after 837 was merged to master.

.gitignore, src/commander.ts, src/data-expander.ts, src/executor.ts, src/git-data.ts, src/handler.ts, src/job.ts, src/mutex.ts, src/parser.ts, src/utils.ts, src/variables-from-files.ts, tsconfig.json
Sonarcloud got smarter overnight, fix them code smells and bug.
=> Sonarcloud got smarter overnight, fix them code smells and bug.

src/job.ts
=> Fix bug in service healthchecking that keeps wait-for-it alive for longer than it needs

src/data-expander.ts, src/job.ts, src/parser.ts, tests/test-cases/services/.gitlab-ci.yml, tests/test-cases/services/integration.services.test.ts
=> add support for service variables

src/parser.ts, tests/test-cases/parallel-matrix/integration.parallel-matrix.test.ts
To show them job names like gitlab.com does
=> Add colon to parallel matrix job name

src/job.ts
Starts services in parallel. Significant speed up with many services or long health checks.
=> Parallel service start

src/handler.ts
```
PASS  tests/test-cases/dind/integration.dind.test.ts (32.812 s)
PASS  tests/test-cases/parallel-matrix/integration.parallel-matrix.test.ts (56.924 s)
PASS  tests/test-cases/services/integration.services.test.ts (25.206 s)
Test Suites: 94 passed, 94 total
Tests:       207 passed, 207 total
Snapshots:   3 passed, 3 total
Time:        58.845 s
Ran all test suites.
mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ docker container ls
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ docker volume ls
DRIVER    VOLUME NAME
local     6d1c1f7d7a9934e70f1b503b47a449973394f72c220dee986fa0bd4551ceccf2
local     11f151db68010819eb72a32d5262d125cb508c3a13b1e1dea2f0b1bb68788de8
local …
```
=> Bugfix resource cleanup

src/data-expander.ts, src/parser.ts, tests/test-cases/extends/.gitlab-ci.yml
=> Make extends part of complex object/list expanding

src/data-expander.ts, tests/test-cases/image/.gitlab-ci.yml
=> Fix using reference in image string only

package-lock.json, package.json, src/argv.ts, src/executor.ts, src/index.ts, tests/test-cases/concurrency/.gitlab-ci.yml, tests/test-cases/concurrency/__snapshots__/integration.concurrency.test.ts.snap, tests/test-cases/concurrency/integration.concurrency.test.ts
=> Add an option to limit Executor concurrency

src/variables-from-files.ts, tests/test-cases/variable-order/.gitlab-ci.yml, tests/test-cases/variable-order/.home/.gitlab-ci-local/variables.yml, tests/test-cases/variable-order/integration.variable-order.test.ts
=> Use strict regex to more precisely choose variables by environment name

tests/test-cases/trigger/.gitlab-ci.yml, tests/test-cases/trigger/integration.trigger.test.ts
=> Add remote project trigger instruction to trigger test

src/index.ts
This is just a fix of the original MR #490
closes https://github.com/firecow/gitlab-ci-local/issues/217
=> Add tab completion on options

src/index.ts
=> Add flags negation to help

package.json, src/job.ts, tests/test-cases/artifacts-after-afterscript/.gitignore, tests/test-cases/artifacts-after-afterscript/.gitlab-ci.yml, tests/test-cases/artifacts-after-afterscript/integration.artifacts-after-afterscript.test.ts, tests/test-cases/concurrency/__snapshots__/integration.concurrency.test.ts.snap, tests/test-cases/log-padding/__snapshots__/integration.plain.log-padding.test.ts.snap, tests/test-cases/plain/integration.plain.test.ts
* fixed behavior
* adapted existing tests due to changed behavior
* added test to prove correct behavior
refers-to: https://github.com/firecow/gitlab-ci-local/issues/961#issue-1854780884
closes #961
=> Job uploads artifacts after running after-scripts (#961)

src/argv.ts, src/handler.ts, src/job.ts, src/parser.ts, tests/test-cases/parallel-matrix/integration.parallel-matrix.test.ts
- Remove assertion roulette from parallel matrix test
closes #969
=> Fix problem with numbers being passed via environment variables

src/job.ts
=> Don't parse inspect output, just rely on exit code

src/argv.ts, src/index.ts, src/job.ts
=> Add network cli option

src/job.ts
update wait-for-it image to support ARM
=> update wait-for-it image to support ARM

src/git-data.ts, src/predefined-variables.ts, tests/mocks/when-statics.ts, tests/test-cases/predefined-variables/.gitlab-ci.yml, tests/test-cases/predefined-variables/integration.predefined-variables.test.ts
=> adds CI_DEFAULT_BRANCH

src/data-expander.ts, tests/test-cases/cache-paths-undefined-array/.gitlab-ci.yml, tests/test-cases/cache-paths-undefined-array/integration.cache-paths-undefined-array.test.ts
=> Fixing that cache.paths can be undefined

src/data-expander.ts, tests/test-cases/cache-key-invalid-files/.gitlab-ci-empty.yml, tests/test-cases/cache-key-invalid-files/.gitlab-ci-three.yml, tests/test-cases/cache-key-invalid-files/integration.key-invalid-files.test.ts
Ensures that cache:key:files: has length of 1 or 2.
=> Fixes #910

src/job.ts, tests/test-cases/artifacts-dotenv/.gitignore, tests/test-cases/artifacts-dotenv/.gitlab-ci.yml, tests/test-cases/artifacts-dotenv/integration.artifacts-dotenv.test.ts
=> Fix reports.dotenv used in image instruction

src/job.ts
=> Don't use slug in CI_REGISTRY_IMAGE, just use regular project path

src/git-data.ts, src/predefined-variables.ts
Fixes this problem https://github.com/firecow/gitlab-ci-local/issues/921#issuecomment-1840659966
=> Don't blow up entire git remote parsing, just because default branch cannot be found

src/predefined-variables.ts
Closes https://github.com/firecow/gitlab-ci-local/issues/986
=> Add CI_TEMPLATE_REGISTRY_HOST

src/job.ts, src/utils.ts, tests/test-cases/variable-escaping/.gitlab-ci.yml, tests/test-cases/variable-escaping/integration.variable-escaping.test.ts
=> fixes variable escaping

src/index.ts
```yaml
---
test:
image: nginx:alpine
stage: build
script:
- sleep 10
```
before 10 seconds is up, send `SIGINT` signal with `<ctrl-c>` 
run `docker ps` and observe that the container is not getting cleaned up
=> fix: cleanup not getting executed

src/job.ts
did some minor refactoring for the Job.start()
=> refactor: job start function

src/commander.ts, src/job.ts, tests/test-cases/script-failures/.gitlab-ci.yml, tests/test-cases/script-failures/integration.script-failures.test.ts
=> feat: support allow_failure:exit_codes

.gitignore, package-lock.json, package.json, src/index.ts
setup nodemon for easier development
=> chore: setup nodemon for easier development (hot-reloading)

src/argv.ts, src/index.ts, src/job.ts, tests/test-cases/mac-address/.gitlab-ci.yml, tests/test-cases/mac-address/integration.environment.test.ts
=> feat: add argv --container-mac-address

src/job.ts, tests/test-cases/cache-key-files/.gitlab-ci.yml, tests/test-cases/cache-key-files/integration.key-files.test.ts
fixes #1148
quite a ugly fix, let me know if you have better idea
=> fix: cache key not working when referencing $CI_PROJECT_DIR

src/parser-includes.ts, src/parser.ts, tests/cases.test.ts
=> fix: handle empty .gitlab-ci.yml

src/argv.ts, src/handler.ts, src/index.ts, tests/test-cases/argv-cwd/.gitlab-ci-2.yml, tests/test-cases/argv-cwd/.gitlab-ci.yml, tests/test-cases/argv-cwd/integration.artifacts-after-afterscript.test.ts
=> fallback cwd

src/job.ts, src/utils.ts, tests/rules.test.ts
=> Fix: manual job rule bug

src/argv.ts, src/index.ts, src/job.ts, tests/test-cases/artifacts-shell/integration.artifacts-shell.test.ts, tests/test-cases/concurrency/integration.concurrency.test.ts, tests/test-cases/interactive/integration.interactive.test.ts, tests/test-cases/long-running-silent-build-job/long-running-silent-build-job.test.ts, tests/test-cases/trigger/.gitlab-ci.yml, tests/test-cases/variable-escaping/integration.variable-escaping.test.ts, tests/test-cases/variables-null/integration.variables-null.test.ts
closes #1171
merge https://github.com/firecow/gitlab-ci-local/pull/1186 in first
=> feat: implement shell executor no image

.npmignore
fixes #1190
hopefully this fixes the missing schema.json
or do we also need this? 
https://github.com/firecow/gitlab-ci-local/issues/1187#issuecomment-2065117413
=> fix: schema.json missing in npm packages

package.json
This should include the schema.json in the npm package.
Related to #1187
=> add schema.json to files for npm package

src/job.ts, tests/test-cases/artifacts-dotenv/.gitlab-ci.yml, tests/test-cases/artifacts-dotenv/integration.artifacts-dotenv.test.ts
fixes #1196 
@PigeonF, nice fix, note that i've made the following changes https://github.com/firecow/gitlab-ci-local/pull/1198/commits/9dcaf902b6a6323a76cc8b911ee582d93b1042d9
=> fix: dotenv variables not loaded for service definitions

src/job.ts, tests/test-cases/artifacts-reports-dotenv/.gitlab-ci-issue-1160.yml, tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts
=> feat: multi dotenv file support

src/parser-includes.ts, src/utils.ts, tests/mocks/utils.mock.ts, tests/mocks/when-statics.ts, tests/test-cases/include-component/component/.gitlab-ci.yml, tests/test-cases/include-component/integration.include-component.test.ts, tests/test-cases/include-component/no-component-template-file/.gitlab-ci.yml, tests/utils.test.ts, tests/utils.ts
=> feat: implement include component

src/git-data.ts, tests/git-data.test.ts, tests/mocks/utils.mock.ts, tests/mocks/when-statics.ts, tests/test-cases/cache-docker-mount-globstar/integration.cache-docker-mount-invalid.test.ts, tests/test-cases/cache-docker-mount/integration.cache-docker-mount.test.ts, tests/test-cases/custom-home/integration.custom-home.test.ts, tests/test-cases/include-invalid-project-file-ref/integration.include-invalid-project-ref-file.test.ts, tests/test-cases/include-project-file-ref-with-inner-local/integration.include-project-file-ref-with-inner-local.test.ts, tests/test-cases/include-project-file-ref/integration.include-project-file-ref.test.ts, tests/test-cases/predefined-variables/integration.predefined-variables.test.ts
not too sure how to fix the code smell though
possible fix for #1178 and #921
=> fix: parsing of basic auth remote-url

src/git-data.ts
=> refactor: provide more meaning error when failed to determine default branch

src/utils.ts
Small  refactoring mr for review once 
https://github.com/firecow/gitlab-ci-local/pull/1215
is merged
=> refactor: getRulesResult logic

src/job.ts
- fixes #1220 whereas docker entrypoint changes the cwd
=> fix: ensure that script gets executed in the /gcl-builds dirs

src/job.ts, tests/mocks/utils.mock.ts, tests/test-cases/network-arg/.gitlab-ci.yml, tests/test-cases/network-arg/integration.network-arg.test.ts
=> Handle `host` and `none` networks

src/git-data.ts, src/utils.ts
=> fix: error when using include:component pipeline with ssh protocol 

src/argv.ts, src/index.ts
https://github.com/firecow/gitlab-ci-local/pull/1167#discussion_r1558871053
Whenever we're ready
=> feat: enable json schema validation by default

src/parser-includes.ts, src/utils.ts, tests/utils.test.ts
- fixes https://github.com/firecow/gitlab-ci-local/pull/1239#discussion_r1621839688 @stiv-pro
- refactor unit test
- refactor to use `Utils.spawn` instead of `Utils.bash`
=> fix: include:component should support custom ssh port

src/utils.ts, tests/rules.test.ts
=> early return from rules evaluation after first match

src/argv.ts, src/git-data.ts
=> fix: fragile isInGitRepository

src/parser.ts, src/utils.ts, tests/test-cases/include-inputs/input-templates/default/.gitlab-ci-input-template.yml, tests/test-cases/include-inputs/input-templates/type-validation/array/.gitlab-ci-input-template.yml, tests/test-cases/include-inputs/input-templates/type-validation/array/.gitlab-ci.yml, tests/test-cases/include-inputs/input-templates/types/array/.gitlab-ci-input-template.yml, tests/test-cases/include-inputs/input-templates/types/array/.gitlab-ci.yml, tests/test-cases/include-inputs/integration.include-inputs.test.ts
implements https://docs.gitlab.com/ee/ci/yaml/inputs.html#array-type and some refactoring
resolve #1249
=> feat: implement array input type

src/handler.ts, src/job.ts, tests/test-cases/preview/integration.preview.test.ts
=> fix: --preview should show global variables

src/parser.ts, tests/test-cases/include-inputs/input-templates/types/boolean/.gitlab-ci-input-template.yml, tests/test-cases/include-inputs/input-templates/types/boolean/.gitlab-ci.yml, tests/test-cases/include-inputs/integration.include-inputs.test.ts, tests/test-cases/script-blank/integration.script-blank.test.ts
=> fix: edge cases when boolean include-input got converted into string when it's supposed to be boolean

src/index.ts
=> Fixes #1296

src/parser.ts, src/validator.ts, tests/test-cases/schema-validation/.gitlab-ci-4-errors.yml, tests/test-cases/schema-validation/.gitlab-ci-5-errors.yml, tests/test-cases/schema-validation/.gitlab-ci-6-errors.yml, tests/test-cases/schema-validation/integration.schema-validation.test.ts, tests/utils.ts
=> refactor: use asserts instead of process.exit

package.json, src/schema/schema.json
=> feat(schema): update schema and add script to do it

src/job.ts, tests/test-cases/project-variables-file/.gitlab-ci-issue-1333.yml, tests/test-cases/project-variables-file/.gitlab-ci-local-variables.yml, tests/test-cases/project-variables-file/integration.project-variables-file.test.ts
=> fix: make fileVariables accessible at an earlier stage

src/job.ts, tests/test-cases/after-script/.gitlab-ci.yml
=> fix: afterscript should be reusing the same container

src/commander.ts
This PR adds the ability for `--list-json` to additionally output the `rules` object.
I'm working on a simple [tool](https://github.com/ekohilas/ci-test) that utilises `gitlab-ci-local`s parsing capabilities to do static testing on `.gitlab-ci.yml` files as part of a conference talk, and outputting this data for use would be much appreciated.
Thanks in advance for your support and work on this project 😊
=> Update list-json to contain rules

src/argv.ts, src/index.ts, tests/test-cases/project-variables-file/integration.project-variables-file.test.ts, tests/test-cases/schema-validation/integration.schema-validation.test.ts, tests/utils.ts
add options for disable color, 
main motivation is to simplify our integration tests; no need to add `chalk` or stripAnsi
=> feat: --no-color to disable colored output

src/job.ts, src/write-streams.ts, tests/test-cases/inherit/.gitlab-ci-inherit-variables.yml, tests/test-cases/inherit/integration.test.ts
as per https://docs.gitlab.com/ee/ci/yaml/#inheritvariables
=> feat: implement inherit:variables

src/data-expander.ts, src/parser.ts
small refactoring pre-req before implementing [inherit:default](https://docs.gitlab.com/ee/ci/yaml/#inheritdefault)
=> refactor: refactor data-expander.ts

README.md
Closes https://github.com/firecow/gitlab-ci-local/discussions/1399
=> Add proper windows rsync link

src/job.ts, src/predefined-variables.ts, tests/mocks/utils.mock.ts, tests/test-cases/dependency-proxy/.gitlab-ci.yml, tests/test-cases/dependency-proxy/integration.dependency-proxy.test.ts, tests/test-cases/predefined-variables/integration.predefined-variables.test.ts
resolves #1358 
resolves #1357
=> feat: add dependency proxy variables

src/parser-includes.ts
This reverts commit e66c59d668f506bfcc0e989fd1f9749b16a93d16.
missing integration test
=> Revert "feat: Respect rules for local includes (#1406)"

src/parser-includes.ts, tests/test-cases/include-project-file/.gitlab-ci-3.yml, tests/test-cases/include-project-file/integration.test.ts
cherry-picked #1406 and added integration test 
closes #1011
=> feat: Respect rules specified in local included project

src/argv.ts, src/commander.ts, src/handler.ts, src/job.ts, src/parser-includes.ts, src/parser.ts, tests/test-cases/parent-child/.gitignore, tests/test-cases/parent-child/.gitlab-ci-1.yml, tests/test-cases/parent-child/.gitlab-ci-2.yml, tests/test-cases/parent-child/.gitlab-ci-3.yml, tests/test-cases/parent-child/.gitlab-ci-4.yml, tests/test-cases/parent-child/.gitlab-ci-5.yml, tests/test-cases/parent-child/.gitlab-ci-6.yml, tests/test-cases/parent-child/.gitlab-ci-7.yml, tests/test-cases/parent-child/child-pipeline.yml, tests/test-cases/parent-child/integration.test.ts, tests/test-cases/parent-child/nested-child-1.yml, tests/test-cases/parent-child/nested-child-2.yml
=> feat: implement child-pipeline

src/argv.ts, src/index.ts, src/job.ts, src/parser-includes.ts, src/parser.ts, src/utils.ts, tests/rules-regex.test.ts, tests/rules.test.ts, tests/test-cases/rules-changes/integration.rules-changes.test.ts
=> feat: add evaluate-rule-changes argv to disable evaluation of rules:changes

.github/workflows/build.yml, .gitignore, package-lock.json, package.json, scripts/install-re2-bin.ts, sonar-project.properties, src/parser-includes.ts, src/utils.ts, tests/rules-regex.test.ts
=> feat: use re2 regex engine for rule evaluation

README.md, src/job.ts, tests/test-cases/image/.gitlab-ci.yml, tests/test-cases/image/integration.test.ts, tests/test-cases/predefined-variables/integration.test.ts
closes https://github.com/firecow/gitlab-ci-local/issues/1468
=> Implement GCL_PROJECT_DIR_ON_HOST

tests/test-cases/include-component/integration.test.ts
closes #1477 
should fix the flappy test https://github.com/firecow/gitlab-ci-local/actions/runs/12951808802/job/36127672271
=> fix: flappy test

scripts/install-re2-bin.ts
=> fix: remove hard-coded platformABI

src/job.ts
=> fix: leaking docker network&volume

src/job.ts, tests/test-cases/parent-child/.gitlab-ci-8.yml, tests/test-cases/parent-child/8/.gitlab-ci.yml, tests/test-cases/parent-child/integration.test.ts
=> feat: implement variable-substitution in trigger:include:local

src/job.ts, tests/test-cases/services/.gitlab-ci-3.yml, tests/test-cases/services/integration.test.ts
=> fix: unnamed services should be ignored

.github/workflows/build.yml, src/argv.ts, tests/test-cases/project-variables-file/.gitlab-ci-local-env, tests/test-cases/project-variables-file/.gitlab-ci.yml, tests/test-cases/project-variables-file/integration.test.ts
=> Special handle variable option from .env file to mimic merge like behavior

src/utils.ts, tests/test-cases/rules-exists/.gitlab-ci.yml, tests/test-cases/rules-exists/integration.test.ts
=> feat: support rules:exists:paths

src/job.ts
=> fix: unnecessary cleanup when there's nothing to clean

package-lock.json, package.json, src/parser-includes.ts, tests/parser-includes.test.ts, tests/test-cases/include-component/component-latest-semver/.gitlab-ci.yml, tests/test-cases/include-component/component-major-semver/.gitlab-ci.yml, tests/test-cases/include-component/component-minor-semver/.gitlab-ci.yml, tests/test-cases/include-component/integration.test.ts
implements https://docs.gitlab.com/ci/components/#semantic-version-ranges
closes #1517
=> feat: add support for semantic version ranges for components

src/argv.ts, src/index.ts, src/job.ts
Add option to set custom helper image.
Defaults to current hard-coded docker image.
=> feat: add option to set custom helper image

src/job.ts, src/parser-includes.ts, tests/test-cases/include-local-wildcard/.gitlab-ci-1.yml, tests/test-cases/include-local-wildcard/.gitlab-ci-2.yml, tests/test-cases/include-local-wildcard/.gitlab-ci-3.yml, tests/test-cases/include-local-wildcard/configs/.gitlab-ci.yml, tests/test-cases/include-local-wildcard/configs/subfolder/.gitlab-ci.yml, tests/test-cases/include-local-wildcard/configs/subfolder/subfolder/.gitlab-ci.yml, tests/test-cases/include-local-wildcard/integration.test.ts
https://docs.gitlab.com/ci/yaml/includes/#use-includelocal-with-wildcard-file-paths
=> fix: use regex instead of globby for include:local wildcard file paths implementation

src/executor.ts, tests/test-cases/self-dependency/.gitlab-ci.yml, tests/test-cases/self-dependency/integration.test.ts
=> fix: Prevent hanging on self-referential dependency loops

src/handler.ts, src/job.ts
=> Remove artifacts in start of job instead of relying on --needs

src/parser-includes.ts, tests/test-cases/include-project-file-with-variable/.gitlab-ci-local-variables.yml, tests/test-cases/include-project-file-with-variable/.gitlab-ci.yml, tests/test-cases/include-project-file-with-variable/integration.test.ts, tests/test-cases/include-project-file-with-variable/mock-test-file.yml
=> fix: substitute variable in include:file if it's array of files

src/data-expander.ts, tests/test-cases/reference/.gitlab-ci-3.yml, tests/test-cases/reference/integration.test.ts
=> fix: Bad expansion for nested rules reference

src/utils.ts, tests/rules.test.ts
=> fix: rules regex (!~)[does not match operator] returning wrong result
