src/index.ts

Before if `argv.cwd` was `undefined` it would be converted to the string `"undefined"` resulting in the default `process.cwd()` never being used and we would get an error when running the program that `undefined/.gitlab-ci.yml could not be found`

Fix such that undefined argv.cwd does not get converted to the string "undefined"

---

package-lock.json
package.json
src/commander.ts
src/handler.ts
src/index.ts
src/job.ts
src/mock-write-streams.ts
src/parser.ts
src/process-write-streams.ts
src/types/job-options.ts
src/types/write-streams.ts
src/utils.ts
tests/cases.test.ts
tests/print-funcs.test.ts
tests/test-cases/include-template/.gitlab-ci.yml

Centralize stdout/stderr outputs in a class, that can be mocked.

Mock write streams, so cases.test.ts becomes simpler

---

src/parser.ts
tests/test-cases/project-variables/.gitconfig
tests/test-cases/project-variables/.gitlab-ci-local/variables.yml
tests/test-cases/project-variables/.gitlab-ci.yml
tests/test-cases/project-variables/.home/.gitlab-ci-local/variables.yml
tests/test-cases/project-variables/.home/file-var
tests/test-cases/project-variables/integration.project-variables.test.ts

This PR adds support for configuring project variables in `.gitlab-ci-local/variables.yaml`. If the same variable is configured in both `$HOME/.gitlab-ci-local/variables.yaml` and `$CWD/.gitlab-ci-local/variables.yaml`, the latter gets precedence.

Allow configuring project level variables in `.gitlab-ci-local/variables.yaml`. Fixes #156

---

src/utils.ts

Rsync is copying the builds directory as a sub directory of the previous builds directory when copying files from the container. This is causing the builds directory size to double on every run.

Fix rsync target path for builds directory. Fixes #162

---

src/parser.ts

Since environment variables are always strings, we should load all variables too as string.

Fix: Load variables as string. Fixes #161

---

src/handler.ts
src/utils.ts
tests/test-cases/.gitignore
tests/test-cases/gitignore/.gitconfig
tests/test-cases/gitignore/.gitlab-ci-local/.gitignore
tests/test-cases/gitignore/.gitlab-ci.yml
tests/test-cases/gitignore/integration.gitignore.test.ts

@bcouetil @JoyceBabu 
I was able to reproduce, when ever .gitlab-ci-local/.gitignore wasn't manually git add'ed, the recursive behavior occurs.

Auto generate .gitlab-ci-local/.gitignore file If .gitignore file isn't git add'ed right away, make sure .gitlab-ci-local is excluded from rsync

---

src/parser.ts
tests/test-cases/include-project-file-ref/.gitlab-ci.yml

This normalizes the path to not start with `/` before being passed to
`git archive`. Otherwise it will complain about the path being outside
of the repository.
Fixes #190.

Fix included YAML download failing due to path starting with `/`.

---

src/job.ts

Services are working, but the `--privileged` do not affect them.  
This can be bad for docker-in-docker based jobs.
For example, with this `.gitlab-ci.yml` :
```yaml
myJob:
image: docker:latest
service:
- docker:dind
script:
- docker build -t myRegistry/myImage:latest
- docker push myRegistry/myImage:latest
```
The docker service will be launched but rapidly fail with few errors like this one :
> mount: permission denied (are you root?)
With the **gitlab-runner**, when the [privileged mode](https://docs.gitlab.com/runner/executors/docker.html#use-docker-in-docker-with-privileged-mode) is active, the services are also affected.
In a way to fix the dind use-case and to better emulate the **gitlab-runner** behavior, we should propagate the `--privileged` flag to services.

Propagate the --privileged flag to services

---

src/job.ts
tests/test-cases/custom-home/.gitlab-ci.yml
tests/test-cases/custom-home/.home/.gitlab-ci-local/variables.yml
tests/test-cases/custom-home/integration.custom-home.test.ts

As a user I should be able to overwrite the default predefined variables by re-defining them in my ~/.gitlab-ci-local/variables.yml file.
Closes #220.

Custom home variables can now overwrite GitLab predefined ones

---

src/job.ts
tests/test-cases/artifacts-exclude/.gitconfig
tests/test-cases/artifacts-exclude/.gitlab-ci.yml
tests/test-cases/artifacts-exclude/integration.artifacts-exclude.test.ts

Add support for the gitlab-ci `artifacts: exclude:` syntax including globstar [as seen here](https://docs.gitlab.com/ee/ci/yaml/#artifactsexclude).
This is an example `.gitlab-ci.yml` that exercises this functionality.
``` yaml
stages:
- stage1
- stage2
job1:
stage: stage1
image: debian:stable-slim
script:
- mkdir -p ux
- touch ux/{q,r,s,t}
- mkdir -p foo/bar/baz/.xyzzy
- mkdir -p "foo/qux/qu ux"
- touch foo/{a,b,c,d}
- touch foo/bar/{w,x,y,z}
- touch foo/bar/baz/{m,n,o,p}
- touch foo/qux/{qu,u,v,w,x}
- touch "foo/qux/qu ux/"{g,h,i,j}
- touch foo/bar/baz/.xyzzy/{.e,.f}
- ls -laR .
artifacts:
name: "the-artifacts"
paths:
- foo
- ux
exclude:
- foo/qux/qu ux/**
- foo/bar/**
- foo/bar
- foo/d
- xyzzy/**/*
job2:
stage: stage2
image: debian:stable-slim
script:
- ls -laR .
- '[ -e "ux" ]'
- '[ …
```

job: add support for artifacts: excludes

---

src/types/git-data.ts

`PROJECT_PATH` variable is camel case formatted, even if GitLab do not apply formatting.
I found this bug with a project named `camel-case` which translate in `PROJECT_PATH=camelCase`,
but in a real GitLab instance it was `PROJECT_PATH=camel-case`

Fix PROJECT_PATH generation

---

src/parser-includes.ts
tests/test-cases/include-project-file-ref/.gitlab-ci.yml

This is a relatively simple and somewhat naive fix for #330 that assumes if `value["file"]` isn't a string that it must be an Array and iterates accordingly.

Handle multiple file includes from same project

---

README.md
package-lock.json
src/handler.ts
src/job.ts
src/parser.ts
src/types/job-options.ts
src/variables-from-files.ts
tests/test-cases/custom-home/.gitlab-ci.yml
tests/test-cases/custom-home/.home/.gitlab-ci-local/variables.yml
tests/test-cases/custom-home/integration.custom-home.test.ts

Made it possible to specific environment matchers in `~/.gitlab-ci-local/variables.yml` or `$cwd/.gitlab-ci-local-variables.yml`
Made it possible to specify file content via `file: <content>` property in `~/.gitlab-ci-local/variables.yml` or `$cwd/.gitlab-ci-local-variables.yml`

Enviroment matchers and file content spec in home and project variables.yml

---

src/job-expanders.ts
src/job.ts
src/service.ts
tests/test-cases/image/.gitlab-ci.yml
tests/test-cases/image/integration.image.test.ts
tests/test-cases/services/.gitlab-ci.yml
tests/test-cases/services/integration.services.test.ts

closes #206 
remedy issue with podman https://github.com/firecow/gitlab-ci-local/issues/298
refactor pull image function to avoid `Utils.bash` and `docker image ls` slowness

Use generated gcl-entry script to better comply with entrypoint syntax

---

package-lock.json
package.json
src/executor.ts
src/job.ts
src/parser-includes.ts
src/utils.ts
tests/rules.test.ts
tests/test-cases/rules-exists/integration.rules-exists.test.ts

- Make sure rules.exist is evaluated on parse time, so `--list` and `--list-all` can show proper when value
- Use micromatch over minimatch

Jobs that gets when:never because of rules.exist is shown in --list

---

src/job.ts
tests/test-cases/artifacts-no-shell-out/.gitlab-ci.yml
tests/test-cases/artifacts-no-shell-out/integration.artifacts-no-shell-out.test.ts

- Fix a bug, where files inside `.gitlab-ci-local` could be copied out as an artifact
- Simplify rsync command in `copyArtifactsOut` function

no-shell artifacts bugfix

---

src/job.ts
tests/test-cases/artifacts-shell-fail-always/.gitignore
tests/test-cases/artifacts-shell-fail-always/.gitlab-ci.yml
tests/test-cases/artifacts-shell-fail-always/integration.artifacts-shell-fail-always.test.ts

Currently when artifacts:when is set to always the artifacts of a failed job aren't copied out.
Ref: https://docs.gitlab.com/ee/ci/yaml/#artifactswhen

Support artifacts:when:always

---

src/job.ts
src/predefined-variables.ts

Add CI_JOB_NAME_SLUG

---

src/job.ts

Pull image if podman fails image inspect

---

src/executor.ts

When looking for starting candidates the executor only considers whether past jobs have failed or not when they are `on_success`  (the default) or `on_failure`. However for this purpose it should also check `manual` jobs.
Closes #658

fix(658): Don't run manual jobs if past jobs failed

---

src/git-data.ts

For example, without the `.git` and the ` (fetch)` at the end: 
```
origin	ssh://git@gitlab.my.company.org/groupname/some-project (fetch)
```

Fix regexp to extract project information that fails on some cases.

---

.gitignore
src/job.ts
src/parser.ts
src/validator.ts
tests/test-cases/needs-pipeline/.gitlab-ci.yml
tests/test-cases/needs-pipeline/integration.needs-pipeline.test.ts

**Is your feature request related to a problem? Please describe.**
We currently cannot test a pipeline configuration that is part of a multi-project or parent-child pipeline configuration if a job has a `needs:pipeline` field, even if the dependency can be mocked somehow (e.g. passing some upstream variable on the CLI). The error is something like:
```
needs: [my-needed-job] for my-job could not be found
```
**Describe the solution you'd like**
When a job has needs.pipeline, because it depends in some way on a job from another pipeline we currently fail to validate the pipeline because the needed job isn't in the current list of jobs of the pipeline. However instead of failing, it is more useful to ignore the particular dependency and emit a warning.
**Describe alternatives you've …

Tolerate needs.pipeline

---

README.md

`sudo` did not apply to the redirect

Fix apt sources command

---

examples/docker-in-docker-build/.gitlab-ci-local-env
src/argv.ts
src/index.ts
src/job.ts
tests/test-cases/dind/.gitlab-ci-local-env

I need the ulimit option for `docker run` because I don't want to change the ulimit of the whole system, just the docker images that I run. This commit would enable using this option in the env file to modify the execution of `docker` to contain the `--ulimit nofile=8000:16000` parameter/values.   
Currently, only the values can be modified in the env file like so:
`ULIMIT=8000:16000`  
If this is too specific, I could make it more general - so that the env file can be configured to contain 
`ULIMIT="nofile=8000:16000"`  
Or something similar so that the nofile or nprocs or whatever other option can be set by the user.

Add ulimit configuration option to env file

---

src/argv.ts
src/index.ts
src/parser.ts
tests/test-cases/logPadding/.gitlab-ci.yml
tests/test-cases/logPadding/__snapshots__/integration.plain.logPadding.test.ts.snap
tests/test-cases/logPadding/integration.plain.logPadding.test.ts

See #840 
In some case, the job names can get very long (e.g., for parallel matrix). In this case, it's better if we avoid padding the job name (or at least not try to add 150+ padding length, as it makes the output harder to read)
Example with this job
```yml
my-matrix-job:
stage: .pre
parallel:
matrix:
- MY_VARIABLE:
- 'very long variable name, for example some URL or long command line parameters'
- 'another one but shorter'
script:
- echo "line 1 - FOO=$MY_VARIABLE"
- echo "line 2"
```
- Use `--maxJobNameLength=0` to disable any padding.
```shell
gitlab-ci-local --maxJobNameLength=0
```
- Use `--maxJobNameLength=50` to add a max padding
```shell
gitlab-ci-local --maxJobNameLength=50
```
Leave empty to keep the current behavior

Logs: Add option to add a max padding for the job name

---

README.md
src/argv.ts
src/commander.ts
src/index.ts
src/job.ts
src/validator.ts
tests/test-cases/logTimestamps/.gitlab-ci.yml
tests/test-cases/logTimestamps/integration.plain.logTimestamps.test.ts

Resolves #846
Example output
```shell
❯ gcl --timestamps
parsing and downloads finished in 34 ms
[15:17:52 1.15 ms] build-job  starting shell (build)
[15:17:52 6.44 ms] build-job  $ sleep 1
[15:17:53  1.01 s] build-job  $ echo 'test done'
[15:17:53  1.01 s] build-job  > test done
[15:17:53  1.01 s] build-job  finished in 1.01 s
[15:17:53  838 μs] failed-job starting shell (.post)
[15:17:53 6.34 ms] failed-job $ exit 1
[15:17:53 6.73 ms] failed-job finished in 6.73 ms  FAIL 1
PASS  [ 1.01 s] build-job
FAIL  [6.73 ms] failed-job
pipeline finished in 1.11 s
```

Add option "--timestamps" to show timestamps and job duration  in the logs

---

src/job.ts
tests/test-cases/network-alias-build/.gitlab-ci.yml
tests/test-cases/network-alias-build/integration.network-alias-build.test.ts

By default in gitlab the main job has an alias "build", added build alias to container when services are used.
See https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27060
This enables connecting to the main container using the build alias for example for chromedriver by using "build" as the hostname.

Add "build" alias to main container if services are enabled (with tests)

---

src/data-expander.ts
tests/test-cases/services/.gitlab-ci.yml

Addresses https://github.com/firecow/gitlab-ci-local/issues/904, where `gitlab-ci-local` fails to correctly parse GitLab CI configuration if there is a singular `!reference` in the services field.
closes #904

Allow single references in services field

---

tests/test-cases/artifacts-exclude/integration.artifacts-exclude.test.ts
tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts
tests/test-cases/artifacts-shell/integration.artifacts-shell.test.ts
tests/test-cases/cache-key-files/integration.key-files.test.ts
tests/test-cases/cache-shell/integration.cache-shell.test.ts
tests/test-cases/interactive/integration.interactive.test.ts
tests/test-cases/needs-empty/integration.needs-empty.test.ts
tests/test-cases/never-needs/integration.never-needs.test.ts

https://github.com/firecow/gitlab-ci-local/pull/448 changed what written to stderr, and so removed the following line from all of the tests ```expect(writeStreams.stderrLines).toEqual([]);```. But, some tests had this line as the only check. So, now there are some tests which basically test nothing.  
For example, if you do the following change and you will see that `artifacts-exclude` still pass:
```diff
--- a/tests/test-cases/artifacts-exclude/.gitlab-ci.yml
+++ b/tests/test-cases/artifacts-exclude/.gitlab-ci.yml
@@ -30,8 +30,4 @@ consume-artifacts:
dependencies: [produce-artifacts]
script:
- ls -laR .
-    - '[ -e "ux" ]'
-    - '[ -e "foo/qux/qu" ]'
-    - '[ -e "foo/qux/qu ux" ]'
-    - '[ ! -e foo/bar ]'
-    - '[ ! -e foo/d ]'
+    - '[ ! -e "ux" ]'
+    - '[ ! -e "foo/qux/qu" ]'
+ …
```

Add missing checks to tests

---

.github/workflows/build.yml
package-lock.json
package.json
src/executor.ts
src/handler.ts
src/index.ts
src/job.ts
src/parser.ts
tests/test-cases/artifacts-docker/integration.artifacts-docker.test.ts
tests/test-cases/image/.gitlab-ci-invalid-image.yml
tests/test-cases/image/integration.image.test.ts
tests/test-cases/parallel-matrix/integration.parallel-matrix.test.ts

@naweiss Have a look. See https://github.com/firecow/gitlab-ci-local/discussions/943 for more information.
promise-pool package doesn't throw on promise rejections, and we want that to happen, so developers can see error messages.

Use p-map instead of promise-pool

---

src/git-data.ts
src/predefined-variables.ts
tests/test-cases/predefined-variables/.gitlab-ci.yml
tests/test-cases/predefined-variables/integration.predefined-variables.test.ts

Closes https://github.com/firecow/gitlab-ci-local/issues/1003

fix CI_COMMIT_SHORT_SHA so it's always 8 characters

---

src/index.ts

closes #1012 
```
mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ node --version && node src/index.js --cwd ../mjn-gitlab-ci-debugging/; echo $?
v18.17.1
parsing and downloads finished in 49 ms
failing_job starting shell (test)
failing_job $ exit 1
failing_job finished in 11 ms  FAIL 1  
FAIL  failing_job
pipeline finished in 129 ms
1
```
Still works in nodejs18

Fix bug in on exit handler causing pipelines to return 0 (success)

---

src/index.ts

This PR will make it more clear what's going on in situations like this https://github.com/firecow/gitlab-ci-local/issues/371#issuecomment-1800126554
I can't really unittest it properly at the moment, so I'll leave screenshots on how I tested it here.
Added this to `job.ts` `execScripts` function
Ran `node src/index.js --cwd <path-to-whatever>` and got the following output.

Print AggregateError's properly

---

src/job.ts
tests/test-cases/scripts-as-string/.gitlab-ci.yml
tests/test-cases/scripts-as-string/integration.scripts-as-string.test.ts

#1043: Allow script/before_script/after_script to be strings

---

examples/docker-compose-nodejs/.gitlab-ci.yml
examples/docker-compose-nodejs/README.md

According the documentation at https://docs.docker.com/compose/reference/:
> Effective July 2023, Compose V1 stopped receiving updates and is no longer in new Docker Desktop releases. Compose V2 has replaced it and is now integrated into all current Docker Desktop versions.
The example should not use the old docker-compose command (Compose V1).

Upgrade the example to use the new docker compose plugin.

---

src/job.ts

Container images have to be lowercased. A quick read of <https://docs.gitlab.com/ee/ci/variables/predefined_variables.html> does not mention that GitLab automatically lowercases `CI_REGISTRY_IMAGE`, but it does so in practice (see below)
I don't know if GitLab lowercases only the project path (as in the screenshot), or if it lowercases the `CI_SERVER_HOST` as well. I assume it does both, so I have placed the `toLowerCase` on the outside of the string, instead of after the `this._variables`.

Lowercase `CI_REGISTRY_IMAGE`

---

src/job.ts
src/predefined-variables.ts
tests/test-cases/predefined-variables/.gitlab-ci.yml
tests/test-cases/predefined-variables/integration.predefined-variables.test.ts

Hi, while running the master branch locally, I realized that my change in #1085 actually broke `CI_REGISTRY_IMAGE`. The reason is that the full string gets lowercased (i.e. something like `$ci_registry/some/lowercased/path`), which means `$CI_REGISTRY` does not get resolved (because the variable name was lowercased) 😅 . Thats what I get for not testing properly 🤦 .
I have added some tests now to make sure the behaviour is correct now (incidentally, I checked the [gitlab source code](https://gitlab.com/gitlab-org/gitlab/-/blob/0c47378a58c35c234c4eae0d9274763db1cdc7f1/app/models/project.rb#L1291-1295) and it seems they only lowercase the path, not the host, so this code matches the upstream behaviour more closely).
While writing the test I realized that `CI_PROJECT_PATH_SLUG` also needs to …

Fix `CI_REGISTRY_IMAGE` (again)

---

src/job.ts
tests/test-cases/extra-host/.gitlab-ci.yml
tests/test-cases/extra-host/integration.extra-host.test.ts

When running a `docker:dind` service I realized that the `--extra-host` arguments passed to `gitlab-ci-local` get passed to the running image, but not to the services, which broke the resolution for my finagled `$CI_REGISTRY_IMAGE` in the docker in docker container (since the registry was resolved in the service container when using `docker buildx build --push`).
Since the services already get the same volumes as the main container, I think it makes sense to pass the `extra-host` args as well. What do you think? I don't know how controversial this change is, so if you think this is a bad idea, feel free to close the PR 😅 .
P.S. Is the test fine like this? I mostly cobbled it together by combining the existing [`add-host <test-job>`](https://github.com/firecow/gitlab-ci-local/blob/51542a6a4 …

Add `--extra-host` arguments to services

---

src/data-expander.ts
tests/test-cases/reference/.gitlab-ci-issue-954.yml
tests/test-cases/reference/integration.reference.test.ts

make use of `--preview` in test cases to make it easier to write expected test output and also speed up test suites
and fixes some yaml referenced tag's value did not get flattened which closes #954

fix: some of before_script/after_script failed to be flattened

---

src/argv.ts
src/index.ts
src/parser-includes.ts
tests/test-cases/include-inputs/input-templates/basic-example/.gitlab-ci.yml
tests/test-cases/include-inputs/input-templates/default/.gitlab-ci.yml
tests/test-cases/include-inputs/input-templates/options-validation/.gitlab-ci.yml
tests/test-cases/include-inputs/input-templates/required-inputs/.gitlab-ci.yml
tests/test-cases/include-inputs/input-templates/too-many-functions-in-interpolation-block/.gitlab-ci.yml
tests/test-cases/include-inputs/input-templates/type-validation/boolean/.gitlab-ci.yml
tests/test-cases/include-inputs/input-templates/type-validation/number/.gitlab-ci.yml
tests/test-cases/include-inputs/input-templates/type-validation/string/.gitlab-ci.yml
tests/test-cases/include-inputs/input-templates/type-validation/unsupported/.gitlab-ci.yml
tests/test-cases/include-inputs/input-templates/unknown-interpolation-key-1/.gitlab-ci.yml
tests/test-cases/include-inputs/input-templates/unknown-interpolation-key-2/.gitlab-ci.yml
tests/test-cases/include-local/.gitlab-ci-invalid-config-directory-traversal.yml
tests/test-cases/include-local/.gitlab-ci-invalid-config-relative-path.yml
tests/test-cases/include-local/integration.include-local.test.ts

- `gitlab-ci-local` generates false positive. 
For the two new test cases for the `include-input` test suites,  
when running the config via `gitlab-ci-local` it has no issue, but Gitlab is unable to parse these configs.
- smuggled a [one liner](https://github.com/firecow/gitlab-ci-local/pull/1124/commits/03f84733a31ddd50a0db6ce3fa41f661bc9c038f)

fix: add validation for include local to prevent false valid configurations

---

src/parser.ts
tests/test-cases/duplicated-keys/.gitlab-ci.yml
tests/test-cases/duplicated-keys/integration.environment.test.ts

fixes #1047
Just because gitlab supports this
but personally i find that it is very error prone so added a `WARN` message to alert the users

allow gcl to work with duplicated keys but with warnings

---

src/data-expander.ts
tests/test-cases/reference/integration.reference.test.ts

This fixes #1137
With the original YML in the ticket:
```yaml
my_job:
image: node:lts
script:
- echo 'test'
```
The rendering of the `--preview` option is now safe (no more `image.docker.user: null`):
```bash
$ node ../test-gitlab-ci-local/gitlab-ci-local/src/index.js --preview
---
stages:
- .pre
- build
- test
- deploy
- .post
my_job:
image:
name: node:lts
script:
- echo 'test'
```
And it passes the `ci/lint` validation:
```bash
$ jq --null-input --arg yaml "$(node ../test-gitlab-ci-local/gitlab-ci-local/src/index.js --preview)" '.content=$yaml' \
| curl "https://gitlab.com/api/v4/projects/${PROJECT_ID}/ci/lint" \
--header "Authorization: Bearer ${GITLAB_TOKEN}" \
--header 'Content-Type: application/json' \
--data @- | jq '.errors'
[]
```
I also deleted the `image.docker.user: null` in …

fix(#1137): only add image.docker.user if the value exists

---

src/data-expander.ts

This fixes #1139 
With the original YML in the ticket:
```yml
my_job:
script:
- echo 'test'
my_job2:
needs:
- my_job
script:
- echo 'test'
```
The rendering of the `--preview` option is now safe (no more `needs.need.pipeline: null` and `needs.need.project: null`):
```bash
$ node ../test-gitlab-ci-local/gitlab-ci-local/src/index.js --preview
---
stages:
- .pre
- build
- test
- deploy
- .post
my_job:
script:
- echo 'test'
my_job2:
needs:
- job: my_job
artifacts: true
optional: false
script:
- echo 'test'
```
And it passes the ci/lint validation:
```bash
$ jq --null-input --arg yaml "$(node ../test-gitlab-ci-local/gitlab-ci-local/src/index.js --preview)" '.content=$yaml' \
| curl "https://gitlab.com/api/v4/projects/${PROJECT_ID}/ci/lint" \
--header "Authorization: Bearer ${GITLAB_TOKEN}" \ …
```

fix(#1139): only add needs.need.pipeline and needs.need.project if the value exists

---

src/index.ts
src/job.ts

`docker rm` and `docker volume rm` supports multiple args. 
this should probably be slightly more efficient.
Not too sure why, but the current cleanup also seemed to leave some `docker volume` undeleted
To replicated the issue:
```yaml
job0:
image: bash
script: echo hi
```
```bash
for i in $(seq 1 9); do
gitlab-ci-local
done
```
Run `docker volume ls` and observe that there are remaing `xxxxx-tmp` volume that are not cleaned up

fix: cleanupJobResource

---

tests/test-cases/umask/.gitlab-ci.yml
tests/test-cases/umask/integration.umask.test.ts

a small refactor to the unit test as a pre-requisite to  https://github.com/firecow/gitlab-ci-local/issues/1171
on a side note, should'nt `--umask` be default to `false` instead ? Which should be closer to gitlab-ci default

refactor(umask integration tests): use non root images instead of building it

---

src/job.ts
tests/test-cases/variable-expansion/.gitlab-ci.yml
tests/test-cases/variable-expansion/integration.variable-expansion.test.ts

Fixes the error for the following `gitlab-ci.yml`
```
docker-executor variables with ':
image: alpine
script:
- echo $CI_JOB_NAME
```
```
docker-executor services variables with ':
services:
- nginx
image: alpine
script:
- echo $CI_JOB_NAME
```

fix: escape single quote env var for docker executor

---

src/data-expander.ts

Running the following, 
```yaml
---
variables:
FOO: 1
job:
image: alpine
script:
- echo hello
```
throws the following error,
```
TypeError: val.replace is not a function.
```
Job's variables are casted to `String` as seen:
https://github.com/firecow/gitlab-ci-local/blob/0286e76abe7bd85cb744bb5500904d58029d0de5/src/parser.ts#L121
We might have forgotten to cast the global variable

fix: cast global variable values to string

---

src/validator.ts

fix: remove extra spaces in the yaml dump when ajv validation fails

---

src/job.ts

[Apparently](https://stackoverflow.com/questions/34110416/start-container-with-multiple-network-interfaces) one cannot pass multiple `--network` flags to `docker create`. I stumbled across this when attempting to add a network to a `.gitlab-ci.yml` with a `service` (since the service definition makes gitlab-ci-local create a custom network).
```yml
job:
services:
- docker:dind
image: alpine
script:
- ip a
```
```console
$ docker network create custom-net
$ gitlab-ci-local --network custom-net
parsing and downloads finished in 37 ms
job starting alpine:latest (test)
job copied to docker volumes in 909 ms
job started service image: docker:dind with aliases: docker in 395 ms
job service image: docker:dind healthcheck passed in 1.76 s
Error: Command failed with exit code 1: docker create …
```

fix: Allow specifying multiple networks

---

src/git-data.ts

The regexr comment actually had the solution. @ANGkeith 
// regexr.com/7vjoq
Our current solution dosn't work if projects containers a `.`
`git@github.com:fire/cow/example.com.git`

fix: git remote get-url origin for git:// can contain dots

---

src/argv.ts
src/gitlab-preset.ts
src/index.ts
src/job.ts
tests/mocks/utils.mock.ts
tests/test-cases/gitlab-runner-emulation/.gitlab-ci.yml
tests/test-cases/gitlab-runner-emulation/integration.emulate-runner.test.ts

Added an option to prefill `memory`, `kernel-memory` and  `cpus` docker options based on the configuration of Gitlab's hosted runner. This is useful when attempting to debug performance issue. By default, no limit is applied, the host resources are all available. 
When passing the option `--container-emulate=` with the name of a gitlab hosted runner, the docker resources is limited to the resource available for this class of hosted runner. As of this PR, those are the values
| name | memory | CPU | 
| --- | --- | --- |
| `saas-linux-small` | 8 GB | 2 |
| `saas-linux-medium` | 16 GB | 4 |
| `saas-linux-large` | 32 GB | 8 |
| `saas-linux-xlarge` | 64 GB | 16 |
| `saas-linux-2xlarge` | 128 GB | 32 |
[see the gitlab documentation here](https://docs.gitlab.com/ee/ci/runners/hosted_runners/linux …

[FEATURE] #1217 Added feature to emulate gitlab hosted runner using the `--container-emulate` option with the name of one of the gitlab preset.

---

package-lock.json
package.json
src/git-data.ts
src/job.ts
src/parser-includes.ts
src/utils.ts
tests/mocks/utils.mock.ts
tests/rules.test.ts
tests/test-cases/rules-changes/.gitlab-ci-rules:changes:paths.yml
tests/test-cases/rules-changes/.gitlab-ci.yml
tests/test-cases/rules-changes/integration.rules-changes.test.ts
tests/utils.test.ts

closes #395
npm i micromatch
npm i --save-dev @types/micromatch

feat: implement rules:changes and rules:changes:path

---

src/job.ts
src/parallel.ts
src/parser.ts
src/schema/schema.json
tests/test-cases/parallel/.gitlab-ci.yml
tests/test-cases/parallel/integration.parallel.test.ts
tests/test-cases/predefined-variables/.gitlab-ci.yml
tests/test-cases/predefined-variables/integration.predefined-variables.test.ts

See <https://docs.gitlab.com/ee/ci/yaml/#parallel>.
When writing the test I saw that there was some verification of the schema (e.g. I could not set `parallel: 1`), but when running `gitlab-ci-local` directly it works fine. Is this intended behaviour? There is now an edge case here, which I cannot test for at the moment: Setting `parallel: 1` works on <https://gitlab.com>, but I cannot write a test for it because it does not match the official schema (which is apparently wrong, I have filed <https://gitlab.com/gitlab-org/gitlab/-/issues/462979>).
This fixes #1227 .

Implement plain `parallel:` keyword

---

src/argv.ts
src/index.ts
src/parser.ts
tests/test-cases/artifacts-dotenv/.gitlab-ci.yml
tests/test-cases/extra-host/integration.extra-host.test.ts
tests/test-cases/plain/integration.plain.test.ts
tests/test-cases/services/.gitlab-ci.yml
tests/test-cases/services/integration.services.test.ts

- Remove the enable part from enableJsonSchemaValidation CLI option, no other bool CLI options has the word enable so it seems redundant
- Replace line count in all tests other than plain  (less assertion roulette)
- Replace dnsutils with a maintained one
closes https://github.com/firecow/gitlab-ci-local/issues/1233

Remove defaults from yargs, they cannot be overridden by other GCL mechanism

---

examples/docker-in-docker-build-with-local-registry/.gitlab-ci-local-variables.yml
examples/docker-in-docker-build-with-local-registry/.gitlab-ci.yml
examples/docker-in-docker-build-with-local-registry/README.md

The current example was failing with the CI unable to connect to the registry.
Updating the example to avoid hardcoding IP and exposing 5000 to external network.

update example for docker-in-docker-build-with-local-registry

---

package-lock.json
package.json
src/schema/schema.json
src/validator.ts

```yml
---
test:
environment:
name: test
url: ''
script: hello
```
This make gitlab-ci-local go boom.
But gitlab is fine with it :smile: Which leaves me to believe that they aren't enforcing their json schema string patterns or formats, so let's ignore them for now.

Do not validate formats and remove all string patterns from schema.json

---

src/git-data.ts
src/utils.ts
tests/git-data.test.ts

fix: gitRemoteMatch scp style does not need to end with .git

---

src/parser-includes.ts
tests/test-cases/include-component/component/.gitlab-ci.yml
tests/test-cases/include-component/integration.include-component.test.ts

Previously the `inputs` were not passed along correctly when transforming the include directives.

Fix nested component includes

---

src/parser-includes.ts
src/predefined-variables.ts
tests/test-cases/include-component/component-local/.gitlab-ci.yml
tests/test-cases/include-component/component-local/templates/my-component.yml
tests/test-cases/include-component/integration.include-component.test.ts

Fix #1272
If the project path is the current project and same commit sha, use the local definition of the component.
This makes it possible to test the component locally: https://docs.gitlab.com/ee/ci/components/#test-the-component

Support for testing local component

---

src/git-data.ts
src/index.ts
src/job.ts
src/predefined-variables.ts
tests/test-cases/environment/.gitlab-ci.yml
tests/test-cases/environment/integration.environment.test.ts

Fix https://github.com/firecow/gitlab-ci-local/issues/653, https://github.com/firecow/gitlab-ci-local/issues/1112

Support additional CI variables

---

src/data-expander.ts
src/job.ts
src/parser.ts
src/validator.ts
tests/test-cases/schema-validation/.gitlab-ci-issue-1277.yml
tests/test-cases/schema-validation/integration.schema-validation.test.ts

Fix: #1277 
Do not extend hidden jobs with `default` so that this validates like on GitLab
Showing a warning in this case since GitLab allows running it but shows an error in the pipeline editor:

Improve validation for default and artifacts

---

src/job.ts
src/utils.ts
tests/test-cases/script-failures/.gitlab-ci.yml
tests/test-cases/script-failures/integration.script-failures.test.ts

Currently `allow_failure` gets overwritten if there are no `allow_failure` keys in the `rules` themselves. That is
```yaml
rules:without allow_failure:
allow_failure:
exit_codes: 137
rules:
- when: always
script:
- exit 137
```
Incorrectly sets `allow_failure` to `false`, even though no setting is set on the `rules`.

Fix `allow_failure` when combined with `rules`

---

src/job.ts
src/utils.ts
tests/test-cases/cache-key-files/.gitlab-ci.yml
tests/test-cases/cache-key-files/integration.key-files.test.ts

fix: should not crash when cache:key:files files don't exist

---

src/parser.ts
tests/test-cases/include-inputs/input-templates/interpolation-repeat/.gitlab-ci-input-template.yml
tests/test-cases/include-inputs/input-templates/interpolation-repeat/.gitlab-ci.yml
tests/test-cases/include-inputs/integration.include-inputs.test.ts

A template like
```yml
---
spec:
inputs:
name:
---
job $[[ inputs.name ]] $[[ inputs.name ]]:
script:
- echo $[[ inputs.name ]]$[[ inputs.name ]]
```
currently ends up looking like
```yaml
job name $[[ inputs.name ]]:
script:
- echo name$[[ inputs.name ]]
```
after substitution.
The fix is to make the regex parsing the `$[[ ]]` part more permissive.

fix: Allow repeated include inputs interpolation

---

src/job.ts
tests/test-cases/umask/.gitlab-ci.yml
tests/test-cases/umask/integration.umask.test.ts

While checking https://github.com/firecow/gitlab-ci-local/issues/1297 I got an error with (essentially) the following CI file
```yaml
---
build:
image:
name: gcr.io/kaniko-project/executor:v1.23.0-debug
entrypoint: [""]
script:
- ls
```
failed for me with
```console
$ gitlab-ci-local --umask=false
Using fallback git commit data
Unable to retrieve default remote branch, falling back to `main`.
Using fallback git remote data
parsing and downloads finished in 49 ms.
json schema validated in 206 ms
build starting gcr.io/kaniko-project/executor:v1.23.0-debug (test)
Error: Command failed with exit code 1: docker run --rm gcr.io/kaniko-project/executor:v1.23.0-debug sh -c echo "$(id -u):$(id -g)"
Error: unknown command "sh" for "executor"
Run 'executor --help' for usage.
at makeError …
```

Fix `umask=false` for images without a shell entrypoint

---

src/job.ts
src/utils.ts
tests/test-cases/rules-changes/.gitlab-ci-rules:changes:paths.yml
tests/test-cases/rules-changes/.gitlab-ci.yml
tests/test-cases/rules-changes/integration.rules-changes.test.ts

This enables common `parallel:matrix` configurations like
```yaml
matrix:
image: alpine
parallel:
matrix:
- SUBDIR:
- foo
- bar
rules:
- changes:
paths:
- "${SUBDIR}/**/*"
script:
- echo "Job is running"
```

Expand variables in `rules:changes`

---

src/job.ts
tests/test-cases/network-arg/integration.network-arg.test.ts

See the discussion in #1300 for more details. Basically, we want to add the service network on container creation instead of afterwards with `podman network connect`, because of the default network mode when using podman.
Since we cannot mix `--network={host,none}` with a user defined network, we cannot use services with `--network={host,none}` mode, so instead of letting the docker/podman command fail, throw a more user friendly `AssertionError.`
Closes #1300 .

fix: Enable `services` for podman executable

---

examples/docker-in-docker-build-with-local-registry/.gitlab-ci.yml
examples/docker-in-docker-build/.gitlab-ci.yml
examples/docker-swarm-php/.gitlab-ci.yml
tests/test-cases/artifacts-reports-dotenv/.gitignore
tests/test-cases/dind-no-tls/.gitlab-ci.yml
tests/test-cases/dind-no-tls/integration.dind-no-tls.test.ts
tests/test-cases/dind-tls/.gitlab-ci.yml

The `dind-no-tls` test fails for me locally because I do not have `iptables`. The fix is to update the `dind` image that is used (more recent versions pick up `nftables`). While I was at it, I also updated the other `docker` references to use `cli` instead of `stable` (the stable tag has not been updated in 4 years).
I'm not sure if this is a quirk of my global configuration, but for the artifacts tests the tests generate `.env` files that are then picked up by git as untracked, so I have added them to the `.gitignore`.

Fix some flaky tests

---

src/utils.ts
tests/rules.test.ts

Because the variables in the `rules:if` evaluation are interpolated using `JSON.stringify`, any `\` characters are escaped to `\\`, which makes e.g. regexes that are expanded from variables invalid. The solution is to unescape the `JSON.stringify` output again.
Before the test case
```javascript
const ruleIf = "$TAG =~ $TAG_REGEX";
const val = Utils.evaluateRuleIf(ruleIf, {TAG: "prefix/1.0.0", TAG_REGEX: "/^prefix\\/.+/"});
```
would expand to `"prefix/1.0.0".match(/^prefix\\/.+/) != null`.
Now it expands to `"prefix/1.0.0".match(/^prefix\/.+/) != null`

fix: Do not escape backslashes during rules:if evaluation

---

src/parser.ts
tests/test-cases/when/.gitlab-ci.yml
tests/test-cases/when/integration.when.test.ts

fixes #1328
https://docs.gitlab.com/ee/ci/yaml/#when

fix: handle edge cases of jobs:when where the value `never` is considered invalid

---

src/schema/schema.json

See <https://gitlab.com/gitlab-org/gitlab/-/merge_requests/155478>.
Fixes #1307.
Follow up to #1309, which added an easy way to update the schema, but did not actually contain the upstream fix which adds the `annotations` keyword to the schema.

chore(schema): Update schema to 379d3cbbce2c5db13840919a8f3c14bab5f9bca5

---

tests/test-cases/gitlab-runner-emulation/integration.emulate-runner.test.ts
tests/test-cases/network-arg/integration.network-arg.test.ts

When the `handler` throws error in the test suites, `cleanupJobResources` is not called, resulting in dangling resources. This should fix the `openHandle` warning when running the tests 
- initially had another idea which is to wrap the handler with a try/finally block
to https://github.com/firecow/gitlab-ci-local/blob/master/src/handler.ts#L24, but it's messy since we're catching the errors in `src/index.ts` so for now went with this, which should be less disruptive

test: improper teardown in jest

---

README.md

Fixes https://github.com/firecow/gitlab-ci-local/issues/1344
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>

Add the `deb [ signed-by=${PPA_KEY_PATH} ]` way (tailored for older OSes)

---

src/utils.ts
tests/rules-regex.test.ts

When running the following
```
> gitlab-ci-local@4.53.0 start
> ts-node --log-error src/index.ts --cwd ../some-dir --list-json
```
The following error occurs
```
Error attempting to evaluate the following rules:
rules:
- if: '"main" && null =~ /\bdependency_scanning\b/ && null == "true"'
as
```javascript
"main" && null.match(/\bdependency_scanning\b/)  != null&& null == "true"
```
```
TypeError: Cannot read properties of null (reading 'match')
at eval (eval at evaluateRuleIf (gitlab-ci-local/src/utils.ts:258:19), <anonymous>:1:20)
at Function.evaluateRuleIf (gitlab-ci-local/src/utils.ts:258:19)
at Function.getRulesResult (gitlab-ci-local/src/utils.ts:181:24)
at new Job (gitlab-ci-local/src/job.ts:217:38)
at gitlab-ci-local/src/parser.ts:179:29
at Function.forEachRealJob …

Fixes undefined vars becoming null and erroring in conditions

---

src/git-data.ts
tests/git-data.test.ts

When `gitlab-ci-local` is run from within gitlab ci, the remote url is `https://gitlab-ci-token:[MASKED]@gitlab.com/user/repo.git`
This PR resolves this issue by updating the regex parsing to handle additional characters.

fix git remote regex parsing to handle additional characters

---

src/job.ts

some cases when `docker run ...` is ran before the image is pulled

refactor: pull docker image earlier

---

package-lock.json
package.json
src/index.ts

npm uninstall ts-node source-map-support @types/source-map-support
npm install --save-dev tsx
Using the following 
```yaml
---
job:
image: test-err
script:
- echo 1
```
The stack trace returns the wrong line number. 
which is possibly related to https://www.github.com/TypeStrong/ts-node/issues/2053, thus replacing `ts-node` with `tsx`

fix: wrong line number in stack trace

---

src/handler.ts

I previously came across an issue where I was getting incorrect output due to cached files.
On realising this, I set the `--fetch-includes` flags, as it was documented that it would always fetch includes even when cached.
However when this flag was enabled, the program returned no output, and short-circuited all other flags.
This is because of the changes seen below, even though this flag value is used elsewhere to determine whether includes should be refetched.
While this is an api breaking change, if I understand the code correctly, it as an acceptable bug fix.
This is because the flag currently doesn't produce any output and only calls `Parser.create`.
However this PR would set it so that the flag does produce the correct output (which if I understand correctly won't make a difference …

remove fetch-includes early return

---

src/parser-includes.ts

Currently, `rules` are not respected for local includes (#1011).
This PR adds a check for any `rules` in local includes and doesn't include the file if the rules resolve to `never`.

Respect rules for local includes

---

src/utils.ts
tests/rules-regex.test.ts

fix: Parsing of rules fails in where there is no whitespace near the parentheses

---

src/commander.ts

list-json was returning `null` in json for rules output when the rules were undefined

Fix list-json rules by only returning rules if defined

---

src/index.ts
src/schema/index.ts
tsconfig.json

Reopening of #1422 
In Node 18.18, the following error occurs:
```
npx --yes gitlab-ci-local@latest                                                                                                                                                 
file:///Users/username/.npm/_npx/3f18f2096def1b34/node_modules/gitlab-ci-local/src/index.js:13
import packageJson from "../package.json" with { type: "json" };
^^^^
SyntaxError: Unexpected token 'with'
at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
at async link (node:internal/modules/esm/module_job:68:21)
Node.js v18.18.2
```
This PR fixes the issue by converting json imports to instead use readfilesync and JSON.parse instead, which makes it more …

Fix json import

---

package-lock.json
src/argv.ts
src/index.ts
src/job.ts
tests/test-cases/shell-executor-no-image/.gitlab-ci.yml
tests/test-cases/shell-executor-no-image/integration.shell-executor-no-image.test.ts

Currently if `--shell-executor-no-image=false` is used the runner defaults to `docker.io/ruby:3.1`.
In case isolation is required, there is no option to run the ci in a custom image.
Added --default-image option. 
If set when `--shell-executor-no-image=false`, the value will be used as a image source for the container.
If not set when `--shell-executor-no-image=false`, the default `docker.io/ruby:3.1` will be used.
If set when `--shell-executor-no-image=true` (or not set), warring message is displayed.
If set when `--shell-isolation`, warring message is displayed.
~Fixed typo (or old option name) in `arvg.ts:49`, from `--no-shell-executor-no-image` to  `--shell-executor-no-image`~
Included 3 tests to validate proper runner image/shell is used.

Added --default-image option to be used with --shell-executor-no-image=false

---

README.md

link to #1426 
~npm run esbuild is mandatory to package 
not sure it has to be there~
---
edits:
(npm run esbuild is is only required for creating the single executable binary)

#1426 Update README.md

---

README.md

update readme to reflect the change in behavior of `--fetch-includes` from #1365

docs: update fetch-includes readme

---

src/utils.ts
tests/rules-regex.test.ts

fix: regex should match both single and doubles quoted rhs

---

src/job.ts
src/parser.ts
tests/test-cases/variable-expansion/.gitlab-ci-1.yml
tests/test-cases/variable-expansion/.gitlab-ci-2.yml
tests/test-cases/variable-expansion/integration.test.ts

fix: variable expansion in environment

---

src/variables-from-files.ts

fix: variable value beginning with pipe should not be interpreted as file

---

src/git-data.ts
tests/git-data.test.ts

 fix: refactor and resolve parsing issue with Git data for HTTP schema ending with a slash (/)

---

.github/workflows/build.yml
src/job.ts
tests/test-cases/rules-exists/.gitlab-ci.yml
tests/test-cases/rules-exists/integration.test.ts

closes https://github.com/firecow/gitlab-ci-local/issues/1462

expand values in rules.exists

---

publish-deb

Running gitlab-ci-local will fail on a system that does not have rsync. Add it as a dependency to automatically install it if missing.

fix(deps): Debian package needs rsync to run, so depend on it

---

src/argv.ts
src/index.ts
src/job.ts
tests/test-cases/force-shell-executor/.gitlab-ci.yml
tests/test-cases/force-shell-executor/integration.test.ts

--shell-executor option (#1447)
Allows forcing to always use the shell executor even when there are images declared somewhere. Avoids image downloads and updates when you want a speedy pipeline

feat: add --shell-executor option. (#1447).

---

src/utils.ts
tests/test-cases/variable-expansion/.gitlab-ci-3.yml
tests/test-cases/variable-expansion/integration.test.ts

partially fixes #1473  (The `RELEASE variable does not propagate properly.` issue)
fixes #1492

fix: Utils.expandVariables should be pure and should not modify it's input

---

src/parser-includes.ts

This remoteFileExists check at every launch was slowing down all launches which include components.
See Issue (#1486) for more details.
fixes #1486

fix: (#1486) remove useless remoteFileExists check at every launch

---

src/job.ts
tests/test-cases/services/.gitlab-ci-2.yml
tests/test-cases/services/integration.test.ts

fix: services:entrypoint should support variable expansion and double quotes

---

src/argv.ts
src/index.ts
src/parser.ts
src/schema-error.ts
src/validator.ts
tests/test-cases/schema-validation-ignore/.gitlab-ci-1.yml
tests/test-cases/schema-validation-ignore/.gitlab-ci-2.yml
tests/test-cases/schema-validation-ignore/integration.test.ts
tests/test-cases/schema-validation/integration.test.ts

This should be useful for the following scenarios:
- gitlab-ci-local json schema is outdated
- json schema fails but gitlab.com pipeline still accepts it
closes #1503

feat: partially ignore json schema validation

---

eslint.config.mjs
package-lock.json
package.json
src/argv.ts
src/commander.ts
src/data-expander.ts
src/index.ts
src/job.ts
src/parser-includes.ts
src/parser.ts
src/schema-error.ts
src/schema/index.ts
src/utils.ts
tests/rules-regex.test.ts
tests/test-cases/cache-key-invalid-files/integration.test.ts
tests/test-cases/include-inputs/integration.test.ts
tests/test-cases/log-padding/integration.test.ts
tests/test-cases/parent-child/integration.test.ts
tests/test-cases/predefined-variables/integration.test.ts

Not sure if there's something wrong with my setup.. 
Locally `npm run eslint` i am always getting the following error
```
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0
YOUR TYPESCRIPT VERSION: 5.8.2
Please only submit bug reports when using the officially supported version.
=============
```
Instead, i've decided to upgrade eslint to v9

style: upgrade eslint and enforce consistent linebreak style for operators

---

src/job.ts

fix: gcl-cmd: applet not found error for apple silicon macos podman user

---

src/parser.ts
tests/test-cases/basic-inputs/input-templates/default-no-inputs/.gitlab-ci.yml
tests/test-cases/basic-inputs/integration.test.ts

A tiny fix for parsing inputs. It's for the case when `spec.inputs` are specified in main `.gitlab-ci.yml` with defaults and no inputs provided for the job.
Example:
```
---
spec:
inputs:
foo:
type: string
default: bar
---
job:
script:
- echo $[[ inputs.foo ]]
```

fix: Fix inputs parsing when ctx.inputs is undefined.

---

src/job.ts
src/utils.ts
tests/test-cases/cache-docker/.gitlab-ci.yml
tests/test-cases/cache-docker/integration.test.ts
tests/test-cases/cache-key-files/integration.test.ts
tests/test-cases/cache-key-prefix/.gitlab-ci-1.yml
tests/test-cases/cache-key-prefix/.gitlab-ci-2.yml
tests/test-cases/cache-key-prefix/integration.test.ts
tests/test-cases/cache-shell-fail/integration.test.ts
tests/utils.test.ts

closes #1478
sorry for the big PR i kind of mangled a few stuff into it ...
implements the following enhancement:
- https://docs.gitlab.com/ci/yaml/#cachekeyprefix 
- info/warning log on number of matched cache
- optimize copying of cache to only run once for all path instead of running the cp command for each path

feat: implement cache:key:prefix and some enhancement to make gcl cache work more similar to gitlab.com

---

src/data-expander.ts
tests/test-cases/reference/.gitlab-ci-1.yml
tests/test-cases/reference/.gitlab-ci-2.yml
tests/test-cases/reference/integration.test.ts

fix: extending job with referenced variables should merge and not overwrite

---

src/argv.ts
src/index.ts
src/job.ts

I had problems when running a CI pipeline via gitlab-ci-local on a host that uses podman as container engine. Experimenting with the podman invocation locally (the container init script does some  I found out, that using the `--userns=keep-id` [docs](https://docs.podman.io/en/v4.6.1/markdown/options/userns.container.html) option fixes the problem.
So this adds the flag needed to let gitlab-ci-local with the needed flag in the container executor invocation.

Implement support for podmans userns option

---

src/job.ts
tests/test-cases/cache-key-files/.gitlab-ci-1.yml
tests/test-cases/cache-key-files/.gitlab-ci-2.yml
tests/test-cases/cache-key-files/integration.test.ts

fix: cache.key.files containing `*` and `'` should'nt crash

---

src/job.ts

Issue: with one of my gitlab pipelines, our usage of service directives over parallel executors was causing nodejs errors to be raised when trying to replace dockerCmd strings that for some reason were not strings.
Solution: Force casting the values to be string representations in all cases fixed the issue I was having and is a safer call to make.

Trivial: Cast dockerCmd string replace to string.

---

src/global.ts
src/utils.ts
tests/global.test.ts
tests/test-cases/coverage/.gitlab-ci.yml
tests/test-cases/coverage/integration.test.ts

fix: add pcre regex support to coverage regex

---

src/git-data.ts
src/utils.ts
tests/utils.test.ts

Running gitlab-ci-local for a different worktree (eg `gitlab-ci-local --cwd=../project-b`) would throw an error because the `changedFiles` function executes the git diff subprocess in the current cwd.
This commit fixes it by passing the correct cwd to the subprocess.

fix(git-data): pass cwd to git diff subprocess for out-of-source runs

---

src/job.ts
tests/test-cases/cache-directives/integration.test.ts

should'nt be showing the folllowing warning

fix: expand variable when parsing cache path

---

src/git-data.ts

closes https://github.com/firecow/gitlab-ci-local/issues/1619

Print error.message after warning message in git-data.ts

---

src/argv.ts
src/index.ts
src/job.ts

New param "wait-image" to be able to use a alternative image  
Default is the previously hard-coded one : docker.io/sumina46/wait-for-it:latest
closes #1552

modify the used image wait-for-it #1552

---

src/argv.ts
src/index.ts
src/job.ts

Not sure how to make a test for this. 
Devices like /dev/null are already present in the docker container. So you need a *new* device present on the machine to share with docker.
You could do something like this https://stackoverflow.com/questions/23135589/create-dev-fakedevice-supporting-read-write-and-ioctl to make a new character device but you would need root to install it.
Would docker in docker help here?

add optionto set the docker 'device' command line argument
